# Generated by Django 3.0.5 on 2020-04-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitals',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturecount',
            options={'verbose_name': 'медичний заклад', 'verbose_name_plural': 'медичні заклади'},
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='NomenclatureCount',
        ),
        migrations.AddField(
            model_name='nomenclaturecount',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='covid19.Hospitals', verbose_name='Потреби'),
            preserve_default=False,
        ),
    ]
