# Generated by Django 3.0.5 on 2020-04-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20200405_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitals',
            options={'verbose_name': 'медичний заклад', 'verbose_name_plural': 'медичні заклади'},
        ),
        migrations.AlterModelOptions(
            name='nomenclaturecount',
            options={},
        ),
    ]
