# Generated by Django 3.0.5 on 2020-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_auto_20200405_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclaturecount',
            options={'verbose_name': 'Потреби', 'verbose_name_plural': 'Потреби'},
        ),
        migrations.AlterField(
            model_name='nomenclaturecount',
            name='nayavnist',
            field=models.IntegerField(default=0, verbose_name='Наявність'),
        ),
    ]
